apiVersion: v1
kind: Secret
metadata:
    name: wg-config
    namespace: sabnzbd
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:RTGlGJYM/7bzHBWD3d7VSRr5dr0kBHObUP/X8JWL+BJJNuJW3xYkuGuTwnUfTGbJ42bRQh+2NualP4PTMKV8dmife7481Z9qqX4q9LlzM4gAogl45PW3IMNc7vnK6vLHgc2sES+RBTiwrRlIHhhOm4QN6EZKOLZEbFu30sr8jF+R6bXeHqPkG9nlYo+iaMnKBzIPVd+ESO77kp39T0YhmeciyTGeGnTqZR++n01A1V8PUZfMxQBV5VhWTP7fJnNtcZ1jk+0mjeT4DX2A2eVZfAqnzv95ufVzS6qlpBa/O7KQEXoWrHMuiMx0aJo/0bg8Fpy0pkIq4+yTv+APyn/mGdRsBbp3eKgy88pybHn3O8XQUioHR9y56XZoCdyuFwfIpBlm8GCiY7y7GkyI1NJDF8tH+dsXUMLPmWwwyfFVBytaFejliejR65kBpr+NSz+eIIJKWhQOD/NA9EvxTJkbM6eUpZrugZ4LqBFfhuJoM3ooOCk=,iv:SEhmO5q44w1kKiMS9+Tgakweqve/MC/jcgnjcAEyBsk=,tag:ZTVVwkdSUhISbsxvfo3Wxg==,type:str]
sops:
    lastmodified: "2025-10-19T19:14:27Z"
    mac: ENC[AES256_GCM,data:6Hb6vpHNZm+m5iey1TBcBgLanhu76tRK+It83RxlkEH2ek5dEFUTS/JrtoyrJ15i6Q7cT0LjfBf08VDqWTi+/8msOZebIVgu0fU+nooevT1NcM6tyr0ekjwCz5cd8zjrlHkTQAv8vq8JASZXnC8XLatyHz8emh+ypwWBmXuTjzk=,iv:eKhekgDOkreG48Wwroe4BSwZzoUiJ7uBFiUxGYWZLeo=,tag:NZ4Tu5LAzmVj2vAjFp3i6Q==,type:str]
    pgp:
        - created_at: "2025-10-19T15:11:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+MHqw4a3yaISuC7PH6YqmO5/JjwG4e9bRJO984OzXoYAP
            0/DkPLXfAgB0OoB+gEf4dxAp5MgAtXIoedi7K42p2/UYmpmkfs9tgJfpQ68dCT4y
            ascyNUCT4XQMbRLwANOit7nGV+B5tzfRTVmT/7c6CxdwtyBZd+Vea8VgemZCsJQe
            68KAe5ypx2vsthWyCUurJQEUhWT+SFGmHcleOSzKYnIVJW4Jv6wfmp1sHDk2qzt3
            pFCZ2mpP/iZUUdax0CP0T1jvIgJBHe0hhFwFgh325zSQdw8Nrv91QyHqSZsq2ury
            7lKMhZY1WkZeQRW31ou+eLQAkZoGMTHqn9Q5FFN4WthzY5lF0SE0/Dq3QrL7X6bp
            VPMPqFtL+HxHvTq/cAFp3NaMhs4YKnQLDuck4mmcFkvCmRHzaP9hM8U6Qqgm/cxj
            CI8s6d38ztbZnJW5tfTrU4ADQp82+7kz2DWfbeeLyePETugd2XZQVrDBOBmRlgfy
            3rAZ8NVOwRQjq3hWTfhVrEXLNxteyMXcGVWlvI4e/xr/YjVmDJabynMSvHt9xBb9
            K3+rf64RiQOsBxnthZI6vUDdi+3x2IRAv7kqLo1sZRZucBG/+1vABfqErXrJR/r9
            h6BEwwefLaHMtVZSnscSodTpUDaHbZaFbYfaBKY0hzYdZdoINqMZNwXnR0l0G9LS
            XgED2kF4bx1OvpZJdL3uN0d7vG59mmPfIss+w2852YLZk4HCwmQRBp/PMMA/rgvv
            nwnxcl043T/fcWLe5Sc/hcRUHv83jwfe/d0wsqWca6i/D71MYiniD4alC6P9t5o=
            =QT/b
            -----END PGP MESSAGE-----
          fp: C2A54269A1CD7FEE4C8961AF24BCCA5F1BB96A9A
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
