apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: base
      namespace: istio-system
  interval: 15m
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: ">= 1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      ENABLE_NATIVE_SIDECARS: true
    cni:
      enabled: true
    profile: ambient
    meshConfig:
      enableTracing: true
      defaultProviders:
        metrics:
          - opentelemetry
        accessLogging:
          - opentelemetry
        tracing:
          - opentelemetry
      extensionProviders:
        - name: opentelemetry
          opentelemetry:
            service: k8s-monitoring-alloy-receiver.monitoring
            port: 4317
    global:
      meshID: k8s.callahan.house
    replicaCount: 2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: istiod
