apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
  namespace: istio-system
spec:
  dependsOn:
  - name: istiod
    namespace: istio-system
  releaseName: cni
  chart:
    spec:
      chart: cni
      version: 1.27.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    profile: ambient
    global:
      platform: k3d
