apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
  namespace: istio-system
spec:
  dependsOn:
  - name: istiod
    namespace: istio-system
  interval: 15m
  releaseName: cni
  chart:
    spec:
      chart: cni
      version: ">= 1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    profile: ambient
    global:
      platform: k3d
