apiVersion: v1
kind: Namespace
metadata:
  name: intel
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: intel
spec:
  url: https://intel.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: device-plugin-operator
  namespace: intel
spec:
  releaseName: device-plugin-operator
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel
  dependsOn:
  - name: nfd
    namespace: node-feature-discovery
  - name: cert-manager
    namespace: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
  namespace: intel
spec:
  releaseName: gpu-device-plugin
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel
  dependsOn:
  - name: device-plugin-operator
    namespace: intel

