apiVersion: v1
kind: Namespace
metadata:
  name: local-path-provisioner
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 1h
  url: https://github.com/rancher/local-path-provisioner.git
  ref:
    tag: v0.0.32
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  releaseName: local-path-provisioner
  interval: 1h
  chart:
    spec:
      chart: charts/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: local-path-provisioner
  values:
    storageClass:
      name: local-path
      defaultClass: true
    nodeSelector:
      kubernetes.io/os: linux
    nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
      - /megamind/k8s/dynamic/local-path-provisioner
