apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  releaseName: metrics-server
  interval: 15m
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
  dependsOn:
  - name: istiod
    namespace: istio-system
  values:
    replicas: 1
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: metrics-server
    args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
