apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./common/tailscale
  prune: true
  wait: true
  patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: tailscale-operator
      spec:
        values:
          operatorConfig:
            hostname: lab
  - patch: |
      - op: add
        path: /spec/dependsOn/-
        value:
          name: istiod
          namespace: istio-system
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: oauth
          valuesKey: client-id
          targetPath: oauth.clientId
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: oauth
          valuesKey: client-secret
          targetPath: oauth.clientSecret
    target:
      kind: HelmRelease
      name: tailscale-operator
