apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: tailscale-operator
      version: 1.88.4
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  dependsOn:
  - name: istiod
    namespace: istio-system
  valuesFrom:
  - kind: Secret
    name: tailscale-operator-values
    valuesKey: values
  values:
    operatorConfig:
      hostname: lab
    apiServerProxyConfig:
      allowImpersonation: true
      mode: "true"
