apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-substitutions
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    private_key: ENC[AES256_GCM,data:NTAx8Fusr79zL3W356kdYUzm1iJcckwAny6fwD1q4c5yJiTMVdlknUz5uPA=,iv:yai3scX+UiDAbdKXbafh7P4VF+1QSXj8jPi5bzRj61I=,tag:sZnDXV0LizZH2KfmzTJdZg==,type:str]
    address: ENC[AES256_GCM,data:p12J09tvKG904B0=,iv:yEHUOlvSTYtffXnSkOBwLBO9xT7xRZDBylxNNlquRJA=,tag:7lLcEi2H7qIhPPDkJ7Mapw==,type:str]
    dns: ENC[AES256_GCM,data:JcVs3inoHzQ=,iv:zhz0UTQsOhdNE23CMnqXtjR5b6QK7KvSdw5SfJhdW7M=,tag:ot+COd1tHtVofKfc+ym+DQ==,type:str]
    public_key: ENC[AES256_GCM,data:bRMu+G4z/Et73v461Ka3v+CuwS6rHL6xl3YHzPGL0oXE+U8iUGImIc5GH7U=,iv:sJJLI0/h86BcbRYJ6U3FO/QVFp5RSDfMO3fCunjzctM=,tag:vZC4toMqHOY93VQCVCRltw==,type:str]
    endpoint: ENC[AES256_GCM,data:/NbBPtJorPjNxmLJkIqRPuTZWw==,iv:clZtY8fMg6OXVlndDJFWFK1Y6b+xunwiCl4to3aVyxs=,tag:pTKyphg0eQf1Sy7sLVriYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-10T04:09:49Z"
    mac: ENC[AES256_GCM,data:aEl4Z7JD0pszLJSta+KlF8w2WS8VG/a3R5HQ+fdz/m56TPXjIuSeExFp2/DAawLoQFgkgz7raAXY1N4KlpD+KhHZWmsfEEjr7W0ZJ3BDA4eWCN7QUZZqTfJyDWY9Hv8vgmaKIa4LoDg3czsQgrE6TNfoMvq3Gu+s3dr1NWXn5zE=,iv:aw11JGmfXXZUINQqFCO/8jeG/Y4wS0fAfxgJYJnbOA0=,tag:uCAYMD/Pjf2xQg9SwTcyGw==,type:str]
    pgp:
        - created_at: "2025-10-19T15:11:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+MHqw4a3yaISuC7PH6YqmO5/JjwG4e9bRJO984OzXoYAP
            0/DkPLXfAgB0OoB+gEf4dxAp5MgAtXIoedi7K42p2/UYmpmkfs9tgJfpQ68dCT4y
            ascyNUCT4XQMbRLwANOit7nGV+B5tzfRTVmT/7c6CxdwtyBZd+Vea8VgemZCsJQe
            68KAe5ypx2vsthWyCUurJQEUhWT+SFGmHcleOSzKYnIVJW4Jv6wfmp1sHDk2qzt3
            pFCZ2mpP/iZUUdax0CP0T1jvIgJBHe0hhFwFgh325zSQdw8Nrv91QyHqSZsq2ury
            7lKMhZY1WkZeQRW31ou+eLQAkZoGMTHqn9Q5FFN4WthzY5lF0SE0/Dq3QrL7X6bp
            VPMPqFtL+HxHvTq/cAFp3NaMhs4YKnQLDuck4mmcFkvCmRHzaP9hM8U6Qqgm/cxj
            CI8s6d38ztbZnJW5tfTrU4ADQp82+7kz2DWfbeeLyePETugd2XZQVrDBOBmRlgfy
            3rAZ8NVOwRQjq3hWTfhVrEXLNxteyMXcGVWlvI4e/xr/YjVmDJabynMSvHt9xBb9
            K3+rf64RiQOsBxnthZI6vUDdi+3x2IRAv7kqLo1sZRZucBG/+1vABfqErXrJR/r9
            h6BEwwefLaHMtVZSnscSodTpUDaHbZaFbYfaBKY0hzYdZdoINqMZNwXnR0l0G9LS
            XgED2kF4bx1OvpZJdL3uN0d7vG59mmPfIss+w2852YLZk4HCwmQRBp/PMMA/rgvv
            nwnxcl043T/fcWLe5Sc/hcRUHv83jwfe/d0wsqWca6i/D71MYiniD4alC6P9t5o=
            =QT/b
            -----END PGP MESSAGE-----
          fp: C2A54269A1CD7FEE4C8961AF24BCCA5F1BB96A9A
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
