apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-substitutions
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  sabnzbd_wg_conf: ENC[AES256_GCM,data:O9JlkcQhWLUN2myOK2hYtO4PXxFsF7md1Y70mkwbZe4mgTdUNc619BngThNUzrF2Jur8zchhw8JxtnsYKusoYkZUyaqe35gWWsCPB9c6jr1ZBMoX4QHaxs0Qd4PUAvIgqiWibvwgrH2R16nQotC5T+5+og9EK4+TN6B+HOQ6+085SVSgsmwX/KOKGkjobFIy41L/uPhIfnwoA/KmObrIiHtAdmJ/1FV7ERSSab+Lk05l2zJ/RfpKgJITuPAkSMXN0G0niJu04eH5oQwJeAKnDHAjc/AVoljI2J9W8w9ZfRVEMtgR3O3y/d5CesyuTzARiw4BTnvt3GZrkoKZk1j2OHc5NYAkr2L1M1NPoWI2Cg+wBQBbMutnUlLciD8Kz/HlG+SEmDJGntLYnDSZgXnsTdNfwsQO4+ZNQ+WfSUg1eafud8qLaCWBqqvd8W0hOoMD7JXbxwqqnccOsB53HiXZ1SDx995BBDM4L7fBQrWloF0umEc=,iv:7g3FGZMpvOd7BOr2vyoNvqKovJyzx6usXJQDu8KFNow=,tag:Begm6K1LLqX+kpkUj/cHqA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-02-08T06:09:22Z"
  mac: ENC[AES256_GCM,data:v1UY/8yOC6L3TF8CRf3TWdJivoIlfHxgCNBzn37Y0uQ3gNkhh2+RQgYO7bkj875Az/didL+xy8t4vkiefjIcxeYskgZwumDQUgMFV/NOpdsUzxV3qfZjx5JSk7gIDlAKjC0wB24Td87lEYRzhz8UMJNgEUK1x8zbT8L1BbetRqE=,iv:evM3aDf3pJz7AWD/rOl0ff4Hz2MIcg6UL9nQXxk37bE=,tag:iOhjhRf5Lwvx52WKkbkGQw==,type:str]
  pgp:
    - created_at: "2025-10-19T15:11:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/+MHqw4a3yaISuC7PH6YqmO5/JjwG4e9bRJO984OzXoYAP
        0/DkPLXfAgB0OoB+gEf4dxAp5MgAtXIoedi7K42p2/UYmpmkfs9tgJfpQ68dCT4y
        ascyNUCT4XQMbRLwANOit7nGV+B5tzfRTVmT/7c6CxdwtyBZd+Vea8VgemZCsJQe
        68KAe5ypx2vsthWyCUurJQEUhWT+SFGmHcleOSzKYnIVJW4Jv6wfmp1sHDk2qzt3
        pFCZ2mpP/iZUUdax0CP0T1jvIgJBHe0hhFwFgh325zSQdw8Nrv91QyHqSZsq2ury
        7lKMhZY1WkZeQRW31ou+eLQAkZoGMTHqn9Q5FFN4WthzY5lF0SE0/Dq3QrL7X6bp
        VPMPqFtL+HxHvTq/cAFp3NaMhs4YKnQLDuck4mmcFkvCmRHzaP9hM8U6Qqgm/cxj
        CI8s6d38ztbZnJW5tfTrU4ADQp82+7kz2DWfbeeLyePETugd2XZQVrDBOBmRlgfy
        3rAZ8NVOwRQjq3hWTfhVrEXLNxteyMXcGVWlvI4e/xr/YjVmDJabynMSvHt9xBb9
        K3+rf64RiQOsBxnthZI6vUDdi+3x2IRAv7kqLo1sZRZucBG/+1vABfqErXrJR/r9
        h6BEwwefLaHMtVZSnscSodTpUDaHbZaFbYfaBKY0hzYdZdoINqMZNwXnR0l0G9LS
        XgED2kF4bx1OvpZJdL3uN0d7vG59mmPfIss+w2852YLZk4HCwmQRBp/PMMA/rgvv
        nwnxcl043T/fcWLe5Sc/hcRUHv83jwfe/d0wsqWca6i/D71MYiniD4alC6P9t5o=
        =QT/b
        -----END PGP MESSAGE-----
      fp: C2A54269A1CD7FEE4C8961AF24BCCA5F1BB96A9A
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
