apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
type: generic
stringData:
    client-id: ENC[AES256_GCM,data:Z+jBSrB3m5ag7K9O+DwwQqM=,iv:ftHvkQ3acMGn8XI7/cDD5pvaZK29UJoHkY5YB+Meai8=,tag:aRfUYo/L/8yYP/LC9Sf38Q==,type:str]
    client-secret: ENC[AES256_GCM,data:E5QHIeEhQVyv8s4su/N+uj++0xDXfow27SekbFjgitMz7ZVUYciZqm2zl+GgZ2KOpLCfRo/kM4Zpll+GL/Tm,iv:tThE3oZDH+N3foPgvtABx2XGL6oDbG1wUoE+kALKnqE=,tag:2G7bI1PUJWPlsBfbGs67+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-19T02:10:13Z"
    mac: ENC[AES256_GCM,data:itnLfuSss7TuVM9BabOErpJv2veV7koCVQ+6fjfOcY1hACnL8gq6t4iCPs2QupvscCr0po0TJgQko9cwe1zoLG3sBDWou226DSt7jJX46KVryXekMawiv7PJbz4xg5TNpmCwxzJX05Y1SOqSUp6IzW/dGrNMjje4n2ZBbymmTdk=,iv:wfiej3UKflR4REey6ZtFSmPvmFBrf+2wDNRxpIpn0mY=,tag:2WPhTEo4W3IHAfXJQ7xGig==,type:str]
    pgp:
        - created_at: "2025-02-22T18:16:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/7BG8q7uwF2y5IuLtvtbhnQRJ63pUxrx73Dam0h/y+sKsB
            IrHn8SvBDFnsihrRq8k1z57Z8C/coa5sfs6pcytTK15Nrh3+wkwJXBNfJZ48w8Rb
            s/5LxNthqwSAa5AQnip7vVuFl1GnsJ7dbMFoJnPTWL+TzsttfNkhR2TFdx1oDaho
            O38erZ+OK359qTzqB8UTIWRcEA1PPYIi8hweBociy6Hntvn/mSZcWAbEXfby0AHZ
            ZnyHkiVvuP11VYLTRAXYazjsBKBImZbC0k0+Rskq87++9vOYDvV8h70ry+7JfY9N
            Jzx3ej1kz5/CiCx+vSqH4kaI1ZHAKBkt8PzJ7c7HWLBaXparY60hHxtUvc+mUTpV
            4NSpngd6dNUHwYCMedEv/SdombKDBJ5VoRM5JDRg4z1uRffrRuiNxipRgDiqkYyD
            tknBD2fe/uTjIfuKLtRML5JPzXKIKhXDlWS1YI5SI1Ybn4ZQBGzkD5OXCs7nteV2
            1opi2wnTslvV5gW1sGN2W/0IKvsfRbzfUo2pOXunGHAYLYWgUQl352CzFfIkYM2I
            IyGrKMUYxPv7eBoms1QxtvBd7gI//Ca/Xi6HNoDFryqkKGinocjtKsyXKI8v56CG
            ohbTmb9sLEanRPm0ZbQxUDDV1pWrtOhsuLsOvRJqa8ku8/qXJ8phhm4dWgCml2TS
            XAHkoyX9dmGh5wXkXtNUzvI2cuKlAPMtM0GcA9gwv2TT2CJvgngYLWaYumaI76th
            w1V2lOmuFG+m/xHSH4p5/SbvX+fsFmY4aOgqMPtQXSYjtGRiV2PmS7Le8F1x
            =8bGV
            -----END PGP MESSAGE-----
          fp: C2A54269A1CD7FEE4C8961AF24BCCA5F1BB96A9A
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
