apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: istio-system
spec:
  interval: 15m
  releaseName: base
  chart:
    spec:
      chart: base
      version: ">= 1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
