apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: tailscale-operator
      namespace: tailscale
    - name: prometheus-operator-crds
      namespace: monitoring
  interval: 15m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: ">= 27.4.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    alertmanager:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    server:
      extraArgs:
        web.enable-remote-write-receiver: null
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - prometheus
        tls:
          - hosts:
              - prometheus
