apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: istio-system
spec:
  releaseName: base
  interval: 15m
  chart:
    spec:
      chart: base
      version: 1.27.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
