apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: istio-system
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/infrastructure/istio
  prune: true
  wait: true
  patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: istiod
      spec:
        values:
          global:
            meshID: homeserv
          meshConfig:
            enableTracing: true
            defaultProviders:
              metrics:
              - opentelemetry
              accessLogging:
              - opentelemetry
              tracing:
              - opentelemetry
            extensionProviders:
            - name: opentelemetry
              opentelemetry:
                service: k8s-monitoring-alloy-receiver.k8s-monitoring
                port: 4317
    target:
      kind: HelmRelease
      name: istiod
