apiVersion: v1
kind: Namespace
metadata:
  name: k8s-monitoring
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-monitoring
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/infrastructure/k8s-monitoring
  prune: true
  wait: true
  patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: k8s-monitoring
      spec:
        dependsOn:
        - name: prometheus-operator-crds
        - name: istiod
        - name: tailscale-operator
        - name: loki
        - name: tempo
        - name: mimir
        values:
          cluster:
            name: homeserv
          destinations:
          - name: mimir
            type: prometheus
            url: http://mimir-gateway.mimir/api/v1/push
          - name: loki
            type: loki
            url: http://loki-gateway.loki/loki/api/v1/push
          - name: tempo
            type: otlp
            url: http://tempo-gateway.tempo/otlp/v1/traces
    target:
      kind: HelmRelease
      name: k8s-monitoring
