# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kiali
  namespace: flux-system
spec:
  targetNamespace: kiali
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/applications/kiali
  prune: true
  wait: true
  patches:
  - patch: |
      - op: replace
        path: /spec/dependsOn
        value:
        - name: istiod
          namespace: istio-system
    target:
      kind: HelmRelease
      name: kiali
