apiVersion: v1
kind: Namespace
metadata:
  name: loki
  labels:
    istio.io/dataplane-mode: ambient
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./base/applications/loki
  prune: true
  wait: true
  patches:
  - patch: |-
      spec:
        dependsOn:
        - kind: HelmRelease
          name: prometheus-operator-crds
        - kind: HelmRelease
          name: istiod
        values:
          gateway:
            ingress:
              enabled: true
              ingressClassName: tailscale
              hosts:
              - host: loki
                paths:
                - path: /
                  pathType: Prefix
              tls:
              - hosts:
                - loki
    target:
      kind: HelmRelease
      name: loki
