apiVersion: v1
kind: Namespace
metadata:
  name: mimir
  labels:
    istio.io/dataplane-mode: ambient
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mimir
  namespace: flux-system
spec:
  targetNamespace: mimir
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/applications/mimir
  prune: true
  wait: true
  patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: mimir
      spec:
        dependsOn:
        - kind: HelmRelease
          name: istiod
        - kind: HelmRelease
          name: tailscale-operator
        values:
          gateway:
            enabled: true
            enabledNonEnterprise: true
            ingress:
              enabled: true
              ingressClassName: tailscale
              hosts:
              - host: mimir
                paths:
                - path: /
                  pathType: Prefix
              tls:
              - hosts:
                - mimir
    target:
      kind: HelmRelease
      name: mimir
