apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/infrastructure/tailscale
  prune: true
  wait: true
  patches:
  - patch: |
      - op: add
        path: /spec/values/operatorConfig/hostname
        value: homeserv
      - op: add
        path: /spec/targetNamespace
        value: tailscale
    target:
      kind: HelmRelease
      name: tailscale-operator
  - patch: |
      - op: replace
        path: /spec/dependsOn
        value:
        - name: istiod
          namespace: istio-system
      - op: replace
        path: /spec/valuesFrom
        value:
        - kind: Secret
          name: oauth
          valuesKey: client-id
          targetPath: oauth.clientId
        - kind: Secret
          name: oauth
          valuesKey: client-secret
          targetPath: oauth.clientSecret
    target:
      kind: HelmRelease
      name: tailscale-operator
