apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  releaseName: nfs-subdir-external-provisioner
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
  dependsOn:
  - name: istiod
    namespace: istio-system
  - name: tailscale-operator
    namespace: tailscale
  values:
    storageClass:
      defaultClass: true
    nfs:
      server: 192.168.19.240
      path: /megamind/k8s/dynamic
