apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  dependsOn:
  - name: istiod
    namespace: istio-system
  - name: tailscale-operator
    namespace: tailscale
  interval: 15m
  releaseName: nfs-subdir-external-provisioner
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: ">= 4.0.18"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    storageClass:
      defaultClass: true
    nfs:
      server: 192.168.19.240
      path: /megamind/k8s/dynamic
