# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/main/pkg/config/v1alpha5/schema.json
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab
servers: 1
agents: 3
kubeAPI:
  host: lab.k8s.callahan.house
  hostPort: "10443"
network: k8s-lab
volumes:
- volume: /dev/dri:/dev/dri # GPU passthrough
- volume: /bigdata:/bigdata
- volume: /megamind:/megamind

