# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/main/pkg/config/v1alpha5/schema.json
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab
servers: 1
agents: 0
kubeAPI:
  hostPort: "10443"
network: k8s-lab
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
    - arg: --disable=metrics-server,traefik,servicelb
      nodeFilters:
      - server:*
    - arg: --kubelet-arg=allowed-unsafe-sysctls=net.ipv4.conf.all.src_valid_mark
      nodeFilters:
      - agent:*
      - server:*
volumes:
- volume: /dev/dri:/dev/dri # GPU passthrough
  nodeFilters:
  - agent:*
  - server:*
- volume: /bigdata:/bigdata
  nodeFilters:
  - agent:*
  - server:*
- volume: /megamind:/megamind
  nodeFilters:
  - agent:*
  - server:*
