apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  dependsOn:
  - name: istiod
    namespace: istio-system
  releaseName: kiali
  chart:
    spec:
      chart: kiali-server
      version: 2.16.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: istio-system
  values:
    external_services:
      prometheus:
        url: http://mimir-gateway.monitoring/prometheus
    deployment:
      ingress:
        enabled: true
        override_yaml:
          spec:
            ingressClassName: tailscale
            rules:
            - host: kiali
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kiali
                      port:
                        number: 20001
            tls:
            - hosts:
              - kiali
