apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: tailscale-operator
      namespace: tailscale
  interval: 15m
  releaseName: mimir
  chart:
    spec:
      chart: mimir-distributed
      version: ">= 5.6.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/ports/1/appProtocol
                value: tcp
            target:
              kind: Service
              name: .*-headless$
          - patch: |
              - op: add
                path: /spec/ports/1/appProtocol
                value: grpc
            target:
              kind: Service
              name: ^.+-(?:alertmanager|compactor|distributor|ingester(-zone.*)?|overrides-exporter|querier|query-frontend|store-gateway(-zone.*))$
          - patch: |
              - op: add
                path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
                value: memberlist
              - op: add
                path: /spec/template/spec/containers/0/ports/-
                value:
                  containerPort: 7946
                  name: memberlist
                  protocol: TCP
            target:
              kind: Deployment
              name: ^.+-query-frontend$
  values:
    nginx:
      enabled: false
    alertManager:
      enabled: false
    ruler:
      enabled: false
    query_scheduler:
      enabled: false
    overrides_exporter:
      enabled: false
    gateway:
      enabled: true
      enabledNonEnterprise: true
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - host: mimir
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - mimir
    minio:
      enabled: true
