apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  dependsOn:
  - name: istiod
    namespace: istio-system
  interval: 15m
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: ">= 1.80.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
  - kind: Secret
    name: tailscale-operator-values
    valuesKey: values
  values:
    operatorConfig:
      hostname: lab
    apiServerProxyConfig:
      allowImpersonation: true
      mode: "true"
