apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-values
    namespace: tailscale
type: generic
stringData:
    values: ENC[AES256_GCM,data:I3PURr0QjLmHzo0umOzJh6Uor1Hc5nO07ZZ46Gvlv/yZVKKxB61di6ehl6zPXeD158Rc7Hxwgqd0PSNxzJrh9tp8kL6XLpj3h44/JIQ4EsGkxXPMm8WLL36D9wZqkXAxcMfp5mojI8L2yXtYyD7VeAY3/eyK,iv:zOKrxlsFsoJxy6eejKDGQG7ATxuVtqb1i4O4O6v97nM=,tag:C9OohN2mdbcsH9MroxR9Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-22T18:16:24Z"
    mac: ENC[AES256_GCM,data:IhMTaEujS0xkmXSHedDP/92XCNhPGNyGGhwLIE4mCYnGkSLamot35UJA1svckFJOCiC7b19u3zfluyBmq9iCyBB8bsBX66NbEqR/uHTx0ix/2nnKIb1Y+cXXpg0h2u46cbCs3hU8n+F0VnS97XtJPU1HXviIPfEBLPWiXDyz19Y=,iv:2eO/+CSkRef8NLrrs8jrwA4rXy+ydjb+E8t9j2GHrCM=,tag:atscwXVtb/GaR+G6s1IF9g==,type:str]
    pgp:
        - created_at: "2025-02-22T18:16:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/7BG8q7uwF2y5IuLtvtbhnQRJ63pUxrx73Dam0h/y+sKsB
            IrHn8SvBDFnsihrRq8k1z57Z8C/coa5sfs6pcytTK15Nrh3+wkwJXBNfJZ48w8Rb
            s/5LxNthqwSAa5AQnip7vVuFl1GnsJ7dbMFoJnPTWL+TzsttfNkhR2TFdx1oDaho
            O38erZ+OK359qTzqB8UTIWRcEA1PPYIi8hweBociy6Hntvn/mSZcWAbEXfby0AHZ
            ZnyHkiVvuP11VYLTRAXYazjsBKBImZbC0k0+Rskq87++9vOYDvV8h70ry+7JfY9N
            Jzx3ej1kz5/CiCx+vSqH4kaI1ZHAKBkt8PzJ7c7HWLBaXparY60hHxtUvc+mUTpV
            4NSpngd6dNUHwYCMedEv/SdombKDBJ5VoRM5JDRg4z1uRffrRuiNxipRgDiqkYyD
            tknBD2fe/uTjIfuKLtRML5JPzXKIKhXDlWS1YI5SI1Ybn4ZQBGzkD5OXCs7nteV2
            1opi2wnTslvV5gW1sGN2W/0IKvsfRbzfUo2pOXunGHAYLYWgUQl352CzFfIkYM2I
            IyGrKMUYxPv7eBoms1QxtvBd7gI//Ca/Xi6HNoDFryqkKGinocjtKsyXKI8v56CG
            ohbTmb9sLEanRPm0ZbQxUDDV1pWrtOhsuLsOvRJqa8ku8/qXJ8phhm4dWgCml2TS
            XAHkoyX9dmGh5wXkXtNUzvI2cuKlAPMtM0GcA9gwv2TT2CJvgngYLWaYumaI76th
            w1V2lOmuFG+m/xHSH4p5/SbvX+fsFmY4aOgqMPtQXSYjtGRiV2PmS7Le8F1x
            =8bGV
            -----END PGP MESSAGE-----
          fp: C2A54269A1CD7FEE4C8961AF24BCCA5F1BB96A9A
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
