apiVersion: v1
kind: Secret
metadata:
  name: wg-config
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    PrivateKey = ${private_key}
    Address = ${address}
    DNS = ${dns}
    PostUp = ip route add 10.1.0.0/16 dev eth0
    PostUp = ip route add 10.152.183.0/24 dev eth0
    PreDown = ip route del 10.1.0.0/16 dev eth0
    PreDown = ip route del 10.152.183.0/24 dev eth0

    [Peer]
    PublicKey = ${public_key}
    AllowedIPs = 0.0.0.0/0
    Endpoint = ${endpoint}
