apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: tailscale-operator
      namespace: tailscale
    - name: prometheus
      namespace: monitoring
    - name: loki
      namespace: monitoring
  interval: 15m
  releaseName: k8s-monitoring
  chart:
    spec:
      chart: k8s-monitoring
      version: ">= 2.0.13"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cluster:
      name: k8s.callahan.house
    destinations:
      - name: prometheus
        type: prometheus
        url: http://prometheus-server/api/v1/write
      - name: mimir
        type: prometheus
        url: http://mimir-gateway/api/v1/push
      - name: loki
        type: loki
        url: http://loki-gateway/loki/api/v1/push
      - name: tempo
        type: otlp
        url: http://tempo-gateway/otlp/v1/traces
    clusterMetrics:
      enabled: true
    clusterEvents:
      enabled: true
    podLogs:
      enabled: true
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          http:
            enabled: true
          grpc:
            enabled: true
    prometheusOperatorObjects:
      enabled: true
    alloy-metrics:
      enabled: true
    alloy-logs:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-receiver:
      enabled: true
      alloy:
        extraPorts:
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
