apiVersion: v1
kind: Namespace
metadata:
  name: intel
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: intel
spec:
  url: https://intel.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
  namespace: intel
spec:
  releaseName: gpu-device-plugin
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel

