on: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: istio-system
spec:
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  releaseName: kiali
  interval: 15m
  chart:
    spec:
      chart: kiali-server
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: istio-system
  dependsOn:
  - name: istiod
    namespace: istio-system
  values:
    external_services:
      prometheus:
        url: http://mimir-gateway.monitoring/prometheus
    deployment:
      ingress:
        enabled: true
        override_yaml:
          spec:
            ingressClassName: tailscale
            rules:
            - host: kiali
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kiali
                      port:
                        number: 20001
            tls:
            - hosts:
              - kiali
