apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  dependsOn:
  - name: cni
    namespace: istio-system
  releaseName: ztunnel
  chart:
    spec:
      chart: ztunnel
      version: 1.27.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
