apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  dependsOn:
  - name: cni
    namespace: istio-system
  interval: 15m
  releaseName: ztunnel
  chart:
    spec:
      chart: ztunnel
      version: ">= 1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
