apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/kubernetes-sigs/gateway-api.git
  ref:
    semver: ">= 1.2.0"
