apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  releaseName: prometheus-operator-crds
  interval: 15m
  chart:
    spec:
      chart: prometheus-operator-crds
      version: 24.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
