apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: prometheus-community
  path: charts/kube-prometheus-stack/charts/crds/crds
  prune: true
  timeout: 1m
