apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 15m
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: ">= 3.12.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: metrics-server
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
