apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: tailscale-operator
      namespace: tailscale
    - name: prometheus
      namespace: monitoring
  interval: 15m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: ">= 8.10.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana.ini:
      auth.proxy:
        enabled: true
        header_name: Tailscale-User-Login
        header_property: email
        auto_sign_up: true
      users:
        auto_assign_org: true
        auto_assign_org_role: Admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            uid: loki
            type: loki
            url: http://loki-gateway
            isDefault: false
            jsonData:
              manageAlerts: false
              derivedFields:
                - datasourceUid: tempo
                  matcherRegex: '"(t|T)race(?:_|-)?id":"(\w+)"'
                  name: Trace ID
                  url: "${__value.raw}"
                  urlDisplayLabel: View Trace
          - name: Prometheus
            uid: prom
            type: prometheus
            url: http://prometheus-server
            isDefault: true
            jsonData:
              httpMethod: GET
              manageAlerts: false
              prometheusType: Prometheus
              exemplarTraceIdDestinations:
                - datasourceUid: tempo
                  name: traceID
          - name: Mimir
            uid: mimir
            type: prometheus
            url: http://mimir-gateway/prometheus
            isDefault: false
            jsonData:
              httpMethod: GET
              manageAlerts: false
              prometheusType: Prometheus
              exemplarTraceIdDestinations:
                - datasourceUid: tempo
                  name: traceID
          - name: Tempo
            uid: tempo
            type: tempo
            url: http://tempo-gateway
            isDefault: false
            jsonData:
              traceQuery:
                timeShiftEnabled: true
              httpMethod: GET
              tracesToLogsV2:
                datasourceUid: loki
                filterByTraceId: true
              lokiSearch:
                datasourceUid: loki
              tracesToMetrics:
                datasourceUid: prom
              serviceMap:
                datasourceUid: prom
    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - grafana
      tls:
        - hosts:
            - grafana
