apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 5m0s
  url: https://github.com/kubernetes-sigs/node-feature-discovery.git
  ref:
    tag: v0.18.2

