apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  targetNamespace: node-feature-discovery
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: node-feature-discovery
  path: deployment/overlays/default
  prune: true
  timeout: 1m

