apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: ./house/callahan/k8s/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
