apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: tailscale-operator
      namespace: tailscale
  interval: 15m
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      version: ">= 1.18.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    gateway:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - host: tempo
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - tempo
    minio:
      enabled: true
